// ======================================================================
// \title  BME680.template.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for BME680 component implementation class
// ======================================================================

#include "Components/Sensors/BME680/BME680.hpp"
#include "FpConfig.hpp"

namespace Sensors {

  // ----------------------------------------------------------------------
  // Component construction and destruction
  // ----------------------------------------------------------------------

  BME680 ::
    BME680(const char* const compName) :
      BME680ComponentBase(compName)
  {

  }

  BME680 ::
    ~BME680()
  {

  }

}
