// ======================================================================
// \title  BME680.template.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for BME680 component implementation class
// ======================================================================

#ifndef Sensors_BME680_HPP
#define Sensors_BME680_HPP

#include "Components/Sensors/BME680/BME680ComponentAc.hpp"

namespace Sensors {

  class BME680 :
    public BME680ComponentBase
  {

    public:

      // ----------------------------------------------------------------------
      // Component construction and destruction
      // ----------------------------------------------------------------------

      //! Construct BME680 object
      BME680(
          const char* const compName //!< The component name
      );

      //! Destroy BME680 object
      ~BME680();

  };

}

#endif
